//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: np_client.proto
namespace TunerMessage
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBString")]
  public partial class PBString : global::ProtoBuf.IExtensible
  {
    public PBString() {}
    
    private string _str_value;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"str_value", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string str_value
    {
      get { return _str_value; }
      set { _str_value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBBytes")]
  public partial class PBBytes : global::ProtoBuf.IExtensible
  {
    public PBBytes() {}
    
    private byte[] _byte_value;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"byte_value", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] byte_value
    {
      get { return _byte_value; }
      set { _byte_value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBInt")]
  public partial class PBInt : global::ProtoBuf.IExtensible
  {
    public PBInt() {}
    
    private int _int_value;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"int_value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int int_value
    {
      get { return _int_value; }
      set { _int_value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBUInt")]
  public partial class PBUInt : global::ProtoBuf.IExtensible
  {
    public PBUInt() {}
    
    private uint _uint_value;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uint_value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint uint_value
    {
      get { return _uint_value; }
      set { _uint_value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBLong")]
  public partial class PBLong : global::ProtoBuf.IExtensible
  {
    public PBLong() {}
    
    private long _long_value;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"long_value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long long_value
    {
      get { return _long_value; }
      set { _long_value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBULong")]
  public partial class PBULong : global::ProtoBuf.IExtensible
  {
    public PBULong() {}
    
    private ulong _ulong_value;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ulong_value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong ulong_value
    {
      get { return _ulong_value; }
      set { _ulong_value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBFixed32")]
  public partial class PBFixed32 : global::ProtoBuf.IExtensible
  {
    public PBFixed32() {}
    
    private uint _int_value;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"int_value", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public uint int_value
    {
      get { return _int_value; }
      set { _int_value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBFixed64")]
  public partial class PBFixed64 : global::ProtoBuf.IExtensible
  {
    public PBFixed64() {}
    
    private ulong _long_value;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"long_value", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public ulong long_value
    {
      get { return _long_value; }
      set { _long_value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBFloat")]
  public partial class PBFloat : global::ProtoBuf.IExtensible
  {
    public PBFloat() {}
    
    private float _float_value;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"float_value", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float float_value
    {
      get { return _float_value; }
      set { _float_value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBVector3")]
  public partial class PBVector3 : global::ProtoBuf.IExtensible
  {
    public PBVector3() {}
    
    private float _x;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float x
    {
      get { return _x; }
      set { _x = value; }
    }
    private float _y;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float y
    {
      get { return _y; }
      set { _y = value; }
    }
    private float _z;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"z", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float z
    {
      get { return _z; }
      set { _z = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TMLogin")]
  public partial class TMLogin : global::ProtoBuf.IExtensible
  {
    public TMLogin() {}
    
    private string _username;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"username", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string username
    {
      get { return _username; }
      set { _username = value; }
    }
    private string _password;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string password
    {
      get { return _password; }
      set { _password = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TMLoginOut")]
  public partial class TMLoginOut : global::ProtoBuf.IExtensible
  {
    public TMLoginOut() {}
    
    private bool _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool result
    {
      get { return _result; }
      set { _result = value; }
    }

    private string _nickname = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"nickname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string nickname
    {
      get { return _nickname; }
      set { _nickname = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}